name: Code Quality

on:
    workflow_dispatch:
    pull_request:
        branches: [development, dev, acceptance, staging, main, master]

jobs:
    skip-duplicates:
        continue-on-error: true # Uncomment once integration is finished
        runs-on: ubuntu-latest

        # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}

        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5
              with:
                  # All of these options are optional, so you can remove them if you are happy with the defaults
                  cancel_others: "true"
                  concurrent_skipping: "same_content"
                  skip_after_successful_duplicate: "true"
                  paths_ignore: '["**/README.md", "**/docs/**"]'

    static-analysis:
        needs: skip-duplicates
        if: needs.skip-duplicates.outputs.should_skip != 'true'

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - uses: php-actions/composer@v6
              with:
                  php_version: "8.3"

            - name: Run static analysis
              run: composer analyze

    fixers:
        needs: skip-duplicates
        if: needs.skip-duplicates.outputs.should_skip != 'true'

        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
            - run: npm ci

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - uses: php-actions/composer@v6
              with:
                  php_version: "8.3"

            - name: Run code formatters
              run: composer format

            - uses: stefanzweifel/git-auto-commit-action@v5
              id: auto_commit_action
              with:
                  commit_message: CI 💅
                  commit_user_name: GitHub Action
                  commit_user_email: actions@github.com

            - name: Ignore commit in git blame
              if: steps.auto_commit_action.outputs.changes_detected == 'true'
              run: echo ${{ steps.auto_commit_action.outputs.commit_hash }} >> .git-blame-ignore-revs

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Ignore Dusting commit in git blame
                  commit_user_name: GitHub Action
                  commit_user_email: actions@github.com
